# Generated by Django 4.2.11 on 2026-08-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
